colors:
  raspberry: '#f41f68'
  snow: '#000000'
  cloud: '#3e3e3e'
  rain_cloud: '#e8e8e8'
  storm_cloud: '#969696'
  coal: '#000000'
  grape: '#ab60e6'
  blueberry: '#736ee9'
  navy: '#402d99'
  mint: '#36ba75'
  cream: '#fff2dd'
  midnight: '#5b5194'
  pink: '#f682f1'
  pink_light: '#ffe0f5'
  violet: '#e695ff'
  black: '#692fd5'
  black_bright: '#6b88bf'
  red: '#f0023e'
  red_bright: '#ff7d7d'
  green: '#00bd87'
  green_bright: '#38cf7a'
  yellow: '#ff5c7e'
  yellow_bright: '#ffca66'
  blue: '#0062eb'
  blue_bright: '#7daaff'
  magenta: '#fd28a2'
  magenta_bright: '#ff88e9'
  cyan: '#b72ed9'
  cyan_bright: '#9102eb'
  white: '#002bcf'
  white_bright: '#9b61e8'
  ui_bg: '#e7e5ff'
  background: '#fcfcfc'
  foreground: '#383838'
  filepath: '#161464'
  gitadd: '#84edb8'
  gitchange: '#d9b0fc'
  gitdelete: '#f79c7e'
  gitchangedelete: '#87c7ed'
  swamplime: '#002bcf'
  tabfillfg: '#9b61e8'
  tabfillbg: '#e7e5ff'
  tabselbg: '#9b61e8'
  tabselfg: '#ffffff'
  truewhite: '#ffffff'
  visualbg: '#e3f1ff'
  search: '#b0f5d7'

colorgroups:
  - { group: 'Normal', guifg: 'foreground', guibg: 'background' }
  - { group: 'Darker', guifg: 'foreground', guibg: 'background' }
  - { group: 'ColorColumn', guifg: 'swamplime', guibg: 'ui_bg' }
  - { group: 'Conceal', guifg: 'yellow_bright', gui: 'bold' }
  - { group: 'Cursor', guifg: 'black_bright', guibg: 'white' }
  - { group: 'CursorLine', guifg: 'coal', guibg: 'visualbg' }
  - { group: 'CursorLineNr', guifg: 'magenta', guibg: 'visualbg', gui: 'bold' }
  - { group: 'Directory', guifg: 'cyan' }
  - { group: 'Error', guifg: 'yellow_bright', gui: 'bold' }
  - { group: 'ErrorMsg', guifg: 'red', guibg: 'storm_cloud' }
  - { group: 'FoldColumn', guibg: 'grape' }
  - { group: 'Folded', guifg: 'cloud', guibg: 'grape' }
  - { group: 'LineNr', guifg: 'black_bright', guibg: 'background' }
  - { group: 'MatchParen', guifg: 'cloud', guibg: 'magenta' }
  - { group: 'ModeMsg', guifg: 'cloud', guibg: 'green' }
  - { group: 'Pmenu', guifg: 'swamplime', guibg: 'background' }
  - { group: 'PmenuSel', guifg: 'truewhite', guibg: 'cream' }
  - { group: 'PmenuSbar', guibg: 'background' }
  - { group: 'Search', guifg: 'black', guibg: 'search' }
  - { group: 'SignColumn', guibg: 'background' }
  - { group: 'Title', guifg: 'white', gui: 'bold' }
  - { group: 'Todo', guifg: 'yellow', guibg: 'cream' }
  - { group: 'VertSplit', guifg: 'cloud', guibg: 'cloud' }
  - { group: 'Visual', guifg: 'coal', guibg: 'cream' }
  - { group: 'WarningMsg', guifg: 'red', guibg: 'snow' }
  - { group: 'Access', guifg: 'white_bright', gui: 'bold' }
  - { group: 'Comment', guifg: 'storm_cloud', gui: 'italic' }
  - { group: 'NonText', guifg: 'storm_cloud' }
  - { group: 'Class', guifg: 'magenta', gui: 'italic' }
  - { group: 'Conditional', guifg: 'cyan_bright' }
  - { group: 'Constant', guifg: 'white', gui: 'bold' }
  - { group: 'Delimiter', guifg: 'green' }
  - { group: 'Function', guifg: 'blue' }
  - { group: 'Identifier', guifg: 'white' }
  - { group: 'Module', guifg: 'magenta', gui: 'underline' }
  - { group: 'Number', guifg: 'magenta_bright' }
  - { group: 'PreProc', guifg: 'red_bright' }
  - { group: 'Statement', guifg: 'cyan_bright' }
  - { group: 'Special', guifg: 'red' }
  - { group: 'SpecialKey', guifg: 'yellow' }
  - { group: 'String', guifg: 'magenta' }
  - { group: 'StorageClass', guifg: 'midnight', gui: 'bold' }
  - { group: 'Structure', guifg: 'white_bright' }
  - { group: 'Symbol', guifg: 'yellow' }
  - { group: 'Type', guifg: 'yellow' }
  - { group: 'Underlined', guifg: 'black_bright', gui: 'underline' }
  - { group: 'StatusLine', guifg: 'swamplime', guibg: 'ui_bg' }
  - { group: 'StatusLineNC', guifg: 'background', guibg: 'background' }
  - { group: 'TabLine', guifg: 'tabfillfg', guibg: 'tabfillbg' }
  - { group: 'TabLineFill', guifg: 'tabfillbg', guibg: 'ui_bg' }
  - { group: 'TabLineSel', guifg: 'tabselfg', guibg: 'tabselbg', gui: 'bold' }
  - { group: 'TabLineAltShade', guifg: 'tabfillbg', guibg: 'tabselfg' }
  - { group: 'User1', guifg: 'magenta', guibg: 'ui_bg' }
  - { group: 'User2', guifg: 'background', guibg: 'ui_bg' }
  - { group: 'User3', guifg: 'mint', guibg: 'ui_bg' }
  - { group: 'User4', guifg: 'black_bright', guibg: 'ui_bg' }
  - { group: 'GitGutterAdd', guifg: 'gitadd' }
  - { group: 'GitGutterChange', guifg: 'gitchange' }
  - { group: 'GitGutterDelete', guifg: 'gitdelete' }
  - { group: 'MatchParen', guibg: 'cream' }
  - { group: 'ParenMatch', guibg: 'cream' }
