- repo: myusuf3/numbers.vim
- repo: matthew-brett/vim-rst-sections
  on_ft: rst

- repo: elixir-editors/vim-elixir

- repo: dhruvasagar/vim-table-mode
  on_ft: rst

# Disable rafi's plugins
- { repo: fatih/vim-go, if: 0 }
- { repo: t9md/vim-choosewin, if: 0 }
- { repo: lambdalisue/suda.vim, if: 0 }
- { repo: MattesGroeger/vim-bookmarks, if: 0 }
- { repo: deoplete-plugins/deoplete-go, if: 0 }
- { repo: fszymanski/deoplete-emoji, if: 0 }
- { repo: ludovicchabant/vim-gutentags, if: 0 }
- { repo: itchyny/calendar.vim, if: 0 }
- { repo: t9md/vim-choosewin, if: 0 }
- { repo: benekastah/neomake, if: 0 }
- { repo: christoomey/vim-tmux-navigator, if: 0 }
- { repo: Raimondi/delimitMate, if: 0}
- { repo: kristijanhusak/defx-icons, if: 0 }
